export default interface Conservatory{
    id:null,
    name:string,
    description:string;
    img:string;
    localisation:string;
    price:number;
    phoneN:number;
}
// export class conservatoryDTO implements IConservatory{
//     id:null;
//     name:"";
//     description:"";
//     img:"";
//     localisation:"";
//     price:null;
//     phoneN:null;
//   }
// export default class conservatorys extends conservatoryDTO {
//     constructor(dto: conservatoryDTO){
//       super();
//       Object.assign(this, dto);
//     }
// }
